PUT file://raw_data_source/entsoe_generation_unit.csv.gz @ENTSOE_GENERATION_UNIT_STAGE;
TRUNCATE TABLE EPILOT.RAW.ENTSOE_GENERATION_UNIT_RAW;
COPY INTO EPILOT.RAW.ENTSOE_GENERATION_UNIT_RAW FROM @ENTSOE_GENERATION_UNIT_STAGE FILE_FORMAT = CSV_FILE_FORMAT;
!quit